<?php
define('CNC_SISID', 102);

// Quantidade de subeixos no formulario de delegados
define('QUANTIDADE_MAXIMA_SUBEIXOS', 4);

// Tamanho máximo permitido para upload (em MB)
define('MAX_UPLOAD', 10);

// Categorias de delegado
define('CONFERENCIA_CAT_DELEGADO_DELEGADO', 'D');
define('CONFERENCIA_CAT_DELEGADO_COORDENADOR', 'C');
define('CONFERENCIA_CAT_DELEGADO_DELEGADO_NATO', 'N');

// Perfis
define('CONFERENCIA_PERFIL_SAI', 632);
define('CONFERENCIA_PERFIL_CADASTRO', 633);
define('CONFERENCIA_PERFIL_CONSULTA', 634);
define('CONFERENCIA_PERFIL_DELEGADO', 635);

// Workflow pre cadastro da conferência
define('WF_PRECADASTRO_CONFERENCIA', 106);
define('WF_QUESTIONARIO', 107);

// Estados do workflow da conferência
define('WF_CEU_EM_CADASTRAMENTO', 10601);
define('WF_CEU_AGUARDANDO_APROVACAO', 10602);
define('WF_CEU_CANCELADO', 10603);
define('WF_CEU_APROVADO', 10604);
define('WF_CEU_EM_CORRECAO', 10605);
define('WF_CEU_EM_CORRECAO_CONCLUSAO', 323);
define('WF_CEU_CONCLUIDA', 10606);
define('WF_QUESTIONARIO_PREENCHIMENTO', 10701);
define('WF_QUESTIONARIO_CORRECAO', 325);


// Ações do workflow da conferência
define('WF_CEU_ACAO_CADASTRAMENTO_ENVIAR_APROVACAO', 10601);
define('WF_CEU_ACAO_CORRECAO_ENVIAR_APROVACAO', 10605);
define('WF_CEU_ACAO_APROVADO_ENVIAR_CONCLUIR', 10606);

// Ações do workflow dos questionários
define('WF_CEU_ACAO_NOVO_PREENCHIMENTO_COM_DADOS_BRANCOS', 810);

//Siglas dos Tipos de Conferência
define('TIPO_CONFERENCIA_MUNICIPAL', 'M');
define('TIPO_CONFERENCIA_INTERMUNICIPAL', 'I');
define('TIPO_CONFERENCIA_REGIONAL', 'R');
define('TIPO_CONFERENCIA_VIRTUAL', 'V');
define('TIPO_CONFERENCIA_LIVRE', 'L');
define('TIPO_CONFERENCIA_ESTADUAL', 'E');
define('TIPO_CONFERENCIA_REGIONALTERRITORIAL', 'T');

// Questionários
define('QUESTIONARIO_ESTADUAL', 6);
define('QUESTIONARIO_MUNICIPAL', 4);
define('QUESTIONARIO_INTERMUNICIPAL', 5);

// Abas
define('ABA_CONFERENCIA', 57381);
define('ABA_CONFERENCIA_LIVRE', 57383);
define('ABA_VINCULAR_CEU', 57384);
////////////////////////////////////////////////////////////////////////continuar aqui/////////////////////////////////////////////////////////////////

// Código de MENUS
define('MENU_CEU_LISTAR', 9469);
define('MENU_CEU_SOLICITACAO', 9470);

define('MENU_CEU_DADOS_INICIAIS', 9484);
define('MENU_CEU_UGL_E_GG', 9477);
define('MENU_CEU_MOBILIZACAO_SOCIAL', 9478);
define('MENU_CEU_RH', 9487);
define('MENU_CEU_ARTICULACAO_SNC', 9479);


// Data mínima limite para os períodos da conferência, deve ser escrito nesse formato
define('DATA_MINIMA_CONFERENCIA', '01/01/2013');

//Esferas da conferencia
$arEsferas = array ( array(TIPO_CONFERENCIA_MUNICIPAL, TIPO_CONFERENCIA_INTERMUNICIPAL),
                     array(TIPO_CONFERENCIA_REGIONAL),
                     array(TIPO_CONFERENCIA_VIRTUAL),
                     array(TIPO_CONFERENCIA_ESTADUAL),
                     array(TIPO_CONFERENCIA_REGIONALTERRITORIAL));


// Tipos de questionário
define("TIPO_QUESTIONARIO_UGL_GG", 1);
define("TIPO_QUESTIONARIO_MOBILIZACAO_SOCIAL", 2);
define("TIPO_QUESTIONARIO_ARTICULACAO_SNC", 3);
define("TIPO_QUESTIONARIO_RH", 4);

// Perguntas do questionario
define("PERGUNTA_UGL_GG_CONSTITUIDO", 946);
define("PERGUNTA_UGL_GG_NUMERO_MEMBROS_SOCIEDADE", 949);
define("PERGUNTA_UGL_GG_NUMERO_MEMBROS_ENTORNO", 950);
define("PERGUNTA_UGL_GG_NUMERO_MEMBROS_PODER_PUBLICO", 951);

define("PERGUNTA_UGL_GG_GRP_MEMBROS_UGL_TIPO_DE_MEMBRO", 941);
define("PERGUNTA_UGL_GG_GRP_MEMBROS_GG_TITULARIDADE", 1236);
define("PERGUNTA_UGL_GG_GRP_MEMBROS_GG_TIPO_DE_MEMBRO", 955);

define("PERGUNTA_ART_SNC_PARC_INST_TEMA_ATUACAO", 980);
define("PERGUNTA_ART_SNC_PARC_INST_TEMA_ATUACAO_SECUNDARIA", 1108);
define("PERGUNTA_ART_SNC_PARC_INST_TEMA_ATUACAO_TERCIARIA", 1109);
define("PERGUNTA_ART_SNC_PARC_INST_DURACAO_PARCERIA", 982);
define("PERGUNTA_ART_SNC_PARC_INST_ENVOLVE_RECURSOS", 1017);
define("PERGUNTA_ART_SNC_PARC_INST_TIPO_CONTATO", 985);

define("PERGUNTA_MOBILIZACAO_SOC_TIPO_ATOR", 970);
define("PERGUNTA_MOBILIZACAO_SOC_TEMA", 973);


// Grupos de perguntas do questionário
define("GRUPO_PERGUNTA_UGL_GG_MEMBROS_DO_GG", 421);
define("GRUPO_PERGUNTA_UGL_GG_MEMBROS_DO_UGL", 417);
define("GRUPO_PERGUNTA_MOBILIZACAO_SOCIAL_MAPEAMENTO_SOCIOCULTURAL", 424);
define("GRUPO_PERGUNTA_ARTICULACAO_SNC_PARCERIAS_INSTITUCIONAIS", 425);


// Itens do questionário
define("ITEM_PERGUNTA_UGL_GG_CONSTITUIDO_SIM", 583);
define("ITEM_PERGUNTA_UGL_GG_MEMBRO_SOCIEDADE", 594);
define("ITEM_PERGUNTA_UGL_GG_MEMBRO_ENTORNO", 595);
define("ITEM_PERGUNTA_UGL_GG_MEMBRO_PODER_PUBLICO", 596);


define("ITEM_PERGUNTA_RH_ESPACO",1001);
define("ITEM_PERGUNTA_RH_NOME_COMPLETO",1002);
define("ITEM_PERGUNTA_RH_SEXO",1003);
define("ITEM_PERGUNTA_RH_RG",1004);
define("ITEM_PERGUNTA_RH_ESCOLARIDADE",1005);
define("ITEM_PERGUNTA_RH_FORMACAO",1006);
define("ITEM_PERGUNTA_RH_TIPO_DE_VINCULO",1007);
define("ITEM_PERGUNTA_RH_FUNCAO",1008);
define("ITEM_PERGUNTA_RH_CARGA_HORARIA",1009);